import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alfian.dm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Add logic to determine dark mode preference
  const prefersDarkMode = typeof window !== 'undefined' && window.matchMedia("(prefers-color-scheme: dark)").matches;

  return (
    <html lang="en" className={prefersDarkMode ? 'dark' : ''}>
      <body className={`${inter.className} bg-black-100 text-white-100`}>{children}</body>
    </html>
  );
}
